name: lvlingam
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python == 3.11.09
  - anaconda
  - pip
  - numpy == 1.26.4
  - pandas == 2.2.3
  - Cython == 0.29.34
  - matplotlib == 3.7.0
  - multiprocess == 0.70.15
  - networkx == 2.8.4
  - scipy == 1.15.1
  - sympy == 1.11.1
  - pytorch == 2.3.1